module.exports.STORE = {
  ADD_STORE: "ADD_STORE",
  ADD_STORE_IN_BULK: "ADD_STORE_IN_BULK",
  GET_ALL_STORES: "GET_ALL_STORES",
  GET_SINGLE_STORE: "GET_SINGLE_STORE",
  UPDATE_STORE: "UPDATE_STORE",
  DELETE_STORE: "DELETE_STORE",
};

module.exports.CATEGORY = {
  ADD_CATEGORY: "ADD_CATEGORY",
  ADD_CATEGORY_IN_BULK: "ADD_CATEGORY_IN_BULK",
  GET_ALL_CATEGORY: "GET_ALL_CATEGORY",
  GET_CATEGORY_DETAILS: "GET_CATEGORY_DETAILS",
  UPDATE_CATEGORY: "UPDATE_CATEGORY",
  DELETE_CATEGORY: "DELETE_CATEGORY",
};

module.exports.SUB_CATEGORY = {
  ADD_SUB_CATEGORY: "ADD_SUB_CATEGORY",
  ADD_SUB_CATEGORY_IN_BULK: "ADD_SUB_CATEGORY_IN_BULK",
  GET_ALL_SUB_CATEGORY: "GET_ALL_SUB_CATEGORY",
  GET_SUB_CATEGORY_DETAILS: "GET_SUB_CATEGORY_DETAILS",
  UPDATE_SUB_CATEGORY: "UPDATE_SUB_CATEGORY",
  DELETE_SUB_CATEGORY: "DELETE_SUB_CATEGORY",
};

module.exports.PRODUCT = {
  ADD_PRODUCT: "ADD_PRODUCT",
  ADD_PRODUCT_IN_BULK: "ADD_PRODUCT_IN_BULK",
  GET_ALL_PRODUCT: "GET_ALL_PRODUCT",
  GET_PRODUCT_DETAILS: "GET_PRODUCT_DETAILS",
  UPDATE_PRODUCT: "UPDATE_PRODUCT",
  DELETE_PRODUCT: "DELETE_PRODUCT",
};

module.exports.ON_BOARD = {
  ADD_USER_SESSION: "ADD_USER_SESSION",
  GET_USER_SESSION: "GET_USER_SESSION",
  VERIFY_TOKEN: "VERIFY_TOKEN",
};

module.exports.OTP = {
  VERIFY_OTP: "VERIFY_OTP",
  OTP_SENT: "OTP_SENT",
  OTP_RESENT: "OTP_RESENT",
  REGENERATE_OTP_SAVED: "REGENERATE_OTP_SAVED",
  CHECK_USER_EXISTENCE: "CHECK_USER_EXISTENCE",
  USER_TOKEN_UPDATE: "USER_TOKEN_UPDATE",
  CREATE_USER_PROFILE: "CREATE_USER_PROFILE",
  REMOVE_USER_SESSION: "REMOVE_USER_SESSION",
  UPDATE_USER_PROFILE: "UPDATE_USER_PROFILE",
};

module.exports.HOME = {
  CATEGORY_FOR_HOME: "CATEGORY_FOR_HOME",
  CATEGORY_DETAILS: "CATEGORY_DETAILS",
};

module.exports.ADDRESS = {
  ADD_NEW_ADDRESS: "ADD_NEW_ADDRESS",
  UPDATE_ADDRESS: "UPDATE_ADDRESS",
  REMOVE_ADDRESS: "REMOVE_ADDRESS",
  SET_DEFAULT_ADDRESS: "SET_DEFAULT_ADDRESS",
  GET_ALL_USER_ADDRESSES: "GET_ALL_USER_ADDRESSES",
};

module.exports.FAVOURITES = {
  ADD_FAVOURITES: "ADD_FAVOURITES",
  REMOVE_FAVOURITES: "REMOVE_FAVOURITES",
  GET_ALL_FAVOURITES: "GET_ALL_FAVOURITES",
};
